<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3hQryZP\Braunstetter_PluginBundle_Test_app_src_TestKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3hQryZP/Braunstetter_PluginBundle_Test_app_src_TestKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3hQryZP.legacy');

    return;
}

if (!\class_exists(Braunstetter_PluginBundle_Test_app_src_TestKernelDevDebugContainer::class, false)) {
    \class_alias(\Container3hQryZP\Braunstetter_PluginBundle_Test_app_src_TestKernelDevDebugContainer::class, Braunstetter_PluginBundle_Test_app_src_TestKernelDevDebugContainer::class, false);
}

return new \Container3hQryZP\Braunstetter_PluginBundle_Test_app_src_TestKernelDevDebugContainer([
    'container.build_hash' => '3hQryZP',
    'container.build_id' => '11f4b4b5',
    'container.build_time' => 1631555194,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3hQryZP');
